// data.jsx — contenu bilingue (FR/AR) + valeurs par défaut des Tweaks.
// Tout ce qui est éditable vit dans TWEAK_DEFAULTS (persisté par l'hôte).

const TWEAK_DEFAULTS = /*EDITMODE-BEGIN*/{
  "design": "a",
  "lang": "fr",
  "editText": false,
  "fontScale": 1,
  "cPrimary": "#1E78C8",
  "cNavy": "#0B2E4F",
  "cLime": "#C4DE00",
  "cSoft": "#EDF5FB",
  "fontHeading": "Plus Jakarta Sans",
  "fontBody": "Plus Jakarta Sans",
  "linkRegister": "https://coincarriere.com/register?type=company",
  "linkEmployers": "https://coincarriere.com/fr/employers",
  "heroImageUrl": "assets/hero.png",
  "heroVideoUrl": "",
  "vidVideoUrl": "https://www.youtube.com/embed/4PB7RQsPhkI",
  "testi1_photo": "assets/people/salma.png",
  "testi2_photo": "assets/people/khadija.png",
  "testi3_photo": "assets/people/mourad.png",
  "showProof": true,
  "showProcess": true,
  "showAdv": true,
  "showVid": true,
  "showStats": true,
  "showFinal": true,
  "agencies": [
    { "name": "Aaqar Partners", "logo": "assets/agencies/aaqar-partners.jpg" },
    { "name": "Adima Properties", "logo": "assets/agencies/adima-properties.jpg" },
    { "name": "Badr Immobilier", "logo": "assets/agencies/badr.jpg" },
    { "name": "Agence Bonnet", "logo": "assets/agencies/bonnet.jpg" },
    { "name": "Alamal Immobilier", "logo": "assets/agencies/alamal.jpg" },
    { "name": "Barnes Marrakech", "logo": "assets/agencies/barnes.jpg" },
    { "name": "Bastet Property", "logo": "assets/agencies/bastet.jpg" },
    { "name": "Cantarel Immobilier", "logo": "assets/agencies/cantarel.jpg" },
    { "name": "Cap Alliance", "logo": "assets/agencies/cap-alliance.jpg" },
    { "name": "Feel Home", "logo": "assets/agencies/feel-home.jpg" },
    { "name": "IGL Immo", "logo": "assets/agencies/igl.jpg" },
    { "name": "ImmoBest", "logo": "assets/agencies/immobest.jpg" },
    { "name": "Immoraf", "logo": "assets/agencies/immoraf.jpg" },
    { "name": "Imvalory", "logo": "assets/agencies/imvalory.jpg" },
    { "name": "Leader Immo", "logo": "assets/agencies/leader-immo.jpg" },
    { "name": "Milkiya", "logo": "assets/agencies/milkiya.jpg" },
    { "name": "North Morocco", "logo": "assets/agencies/north-morocco.jpg" },
    { "name": "Noura Immobilier", "logo": "assets/agencies/noura.jpg" },
    { "name": "Plaza Prestige", "logo": "assets/agencies/plaza-prestige.jpg" },
    { "name": "Premium Immobilier", "logo": "assets/agencies/premium.jpg" },
    { "name": "RS Immo", "logo": "assets/agencies/rs-immo.jpg" },
    { "name": "Serraj Immobilier", "logo": "assets/agencies/serraj.jpg" },
    { "name": "Viaprestige", "logo": "assets/agencies/viaprestige.jpg" }
  ],
  "fr": {
    "nav1": "Processus",
    "nav2": "Avantages",
    "nav3": "Témoignages",
    "header_cta": "Publier une annonce",
    "hero_badge": "Espace Employeurs · Immobilier",
    "hero_title": "Recrutez vos agents immobiliers plus rapidement",
    "hero_sub": "Arrêtez de perdre du temps sur Facebook et WhatsApp. Publiez votre offre, recevez des candidatures d'agents qualifiés et embauchez vite — sans trier des dizaines de CV inutiles.",
    "hero_cta": "Publier votre annonce maintenant",
    "hero_note": "Gratuit pour commencer · Sans engagement",
    "hero_media": "Aperçu de l'espace recruteur",
    "proof_kicker": "AGENCES ET ENTREPRISES BIENTOT RECRUTENT SUR COINCARRIERE",
    "testi_title": "Ce que disent les agences",
    "testi_sub": "Des gérants d'agences immobilières partout au Maroc nous font confiance pour recruter leurs agents.",
    "testi1_quote": "On a recruté 2 agents en une semaine. Avant, je passais des heures sur Facebook sans résultat.",
    "testi1_name": "Salma B.",
    "testi1_role": "Gérante d'agence, Casablanca",
    "testi2_quote": "Les candidatures arrivent déjà filtrées. Je ne perds plus de temps avec des profils qui ne correspondent pas.",
    "testi2_name": "Khadija M.",
    "testi2_role": "Directrice d'agence immobilière, Rabat",
    "testi3_quote": "Simple et rapide. Mon équipe suit toutes les candidatures au même endroit, fini les fichiers Excel.",
    "testi3_name": "Mourad E.",
    "testi3_role": "Responsable recrutement, Marrakech",
    "process_kicker": "SIMPLE ET EFFICACE",
    "process_title": "De l'annonce à l'embauche",
    "process_sub": "Un processus clair en 4 étapes pour trouver votre prochain agent immobilier.",
    "step1_title": "Publiez",
    "step1_desc": "Décrivez le poste d'agent et les compétences attendues. Votre annonce est en ligne en quelques minutes.",
    "step2_title": "Recevez",
    "step2_desc": "Les candidats postulent directement. Filtrez par expérience, secteur et localisation.",
    "step3_title": "Évaluez",
    "step3_desc": "Déplacez les candidats dans votre pipeline, ajoutez des notes et planifiez les entretiens.",
    "step4_title": "Embauchez",
    "step4_desc": "Envoyez l'offre à l'agent retenu et suivez la réponse en temps réel.",
    "process_cta": "Voir comment ça marche",
    "adv_kicker": "POURQUOI COINCARRIERE",
    "adv_title": "Tout ce qu'il faut pour recruter vos agents",
    "adv_sub": "Les outils essentiels, sans la complexité. Prêt à l'emploi dès le premier jour.",
    "feat1_title": "Pipeline visuel des candidats",
    "feat1_desc": "Suivez chaque candidat dans un tableau clair. Déplacez-les d'une étape à l'autre d'un simple glissement.",
    "feat2_title": "Recrutement rapide",
    "feat2_desc": "Publiez en 5 minutes et recevez vos premières candidatures le jour même.",
    "feat3_title": "Moins de CV inutiles",
    "feat3_desc": "Des filtres précis écartent les profils hors sujet. Vous ne voyez que les agents pertinents.",
    "feat4_title": "Travail en équipe",
    "feat4_desc": "Invitez vos collègues, partagez des notes et décidez ensemble, sans WhatsApp.",
    "feat5_title": "Outils simples",
    "feat5_desc": "Une interface claire en français et en arabe. Aucune formation nécessaire.",
    "feat6_title": "Meilleure qualité de candidats",
    "feat6_desc": "Attirez des agents motivés grâce à une page d'annonce professionnelle à votre image.",
    "adv_cta": "Découvrir l'espace recruteur",
    "vid_kicker": "TÉMOIGNAGE",
    "vid_title": "Ils recrutent leurs agents avec CoinCarriere",
    "vid_sub": "Découvrez comment des agences immobilières marocaines ont arrêté de galérer sur Facebook.",
    "vid_media": "Vidéo témoignage — gérant d'agence",
    "vid_cta": "Publier mon annonce",
    "stat1_num": "473+",
    "stats_kicker": "EN CHIFFRES",
    "stats_title": "Quelques chiffres clés de CoinCarriere",
    "stat1_label": "Agences & entreprises qui recrutent",
    "stat2_num": "5 137+",
    "stat2_label": "Offres publiées",
    "stat3_num": "100%",
    "stat3_label": "Gratuit pour commencer",
    "final_kicker": "PRÊT À RECRUTER ?",
    "final_title": "Votre prochain recrutement commence ici",
    "final_sub": "Créez votre espace recruteur et publiez votre première annonce en moins de 5 minutes.",
    "final_cta": "Publier votre annonce maintenant",
    "final_note": "Gratuit pour commencer · Aucune carte requise",
    "footer_tagline": "La plateforme de recrutement nouvelle génération.",
    "footer_privacy": "Politique de confidentialité",
    "footer_copy": "© 2026 CoinCarriere — Tous droits réservés."
  },
  "ar": {
    "nav1": "خطوات العمل",
    "nav2": "المزايا",
    "nav3": "آراء العملاء",
    "header_cta": "نشر إعلان",
    "hero_badge": "فضاء أصحاب العمل · العقار",
    "hero_title": "وظّف وكلاءك العقاريين بشكل أسرع",
    "hero_sub": "توقّف عن إضاعة الوقت على فيسبوك وواتساب. انشر عرضك، استقبل ترشيحات وكلاء مؤهّلين ووظّف بسرعة — دون فرز عشرات السير الذاتية غير المفيدة.",
    "hero_cta": "انشر إعلانك الآن",
    "hero_note": "مجاني للبدء · بدون التزام",
    "hero_media": "معاينة فضاء التوظيف",
    "proof_kicker": "وكالات وشركات قريبا توظّف عبر كوان كارّيير",
    "testi_title": "ماذا تقول الوكالات",
    "testi_sub": "مدراء وكالات عقارية في كل أنحاء المغرب يثقون بنا لتوظيف وكلائهم.",
    "testi1_quote": "وظّفنا وكيلين في أسبوع واحد. من قبل كنت أقضي ساعات على فيسبوك دون أي نتيجة.",
    "testi1_name": "سلمى ب.",
    "testi1_role": "مديرة وكالة عقارية، الدار البيضاء",
    "testi2_quote": "الترشيحات تصل مفلترة مسبقًا. لم أعد أضيّع وقتي مع ملفات لا تناسبني.",
    "testi2_name": "خديجة م.",
    "testi2_role": "مديرة وكالة عقارية، الرباط",
    "testi3_quote": "بسيط وسريع. فريقي يتابع كل الترشيحات في مكان واحد، وداعًا لملفات إكسل.",
    "testi3_name": "مراد إ.",
    "testi3_role": "مسؤول التوظيف، مراكش",
    "process_kicker": "بسيط وفعّال",
    "process_title": "من الإعلان إلى التوظيف",
    "process_sub": "مسار واضح في 4 خطوات للعثور على وكيلك العقاري القادم.",
    "step1_title": "انشر",
    "step1_desc": "صف المنصب والمهارات المطلوبة. يصبح إعلانك متاحًا خلال دقائق.",
    "step2_title": "استقبل",
    "step2_desc": "يتقدّم المرشّحون مباشرة. فلتر حسب الخبرة والقطاع والموقع.",
    "step3_title": "قيّم",
    "step3_desc": "حرّك المرشّحين في مسارك، أضف ملاحظات ونظّم المقابلات.",
    "step4_title": "وظّف",
    "step4_desc": "أرسل العرض للوكيل المختار وتابع الرد في الوقت الفعلي.",
    "process_cta": "شاهد كيف يعمل",
    "adv_kicker": "لماذا كوان كارّيير",
    "adv_title": "كل ما تحتاجه لتوظيف وكلائك",
    "adv_sub": "الأدوات الأساسية بدون تعقيد. جاهزة للاستخدام من اليوم الأول.",
    "feat1_title": "مسار مرئي للمرشّحين",
    "feat1_desc": "تابع كل مرشّح في لوحة واضحة. حرّكه من مرحلة إلى أخرى بسحبة واحدة.",
    "feat2_title": "توظيف سريع",
    "feat2_desc": "انشر في 5 دقائق واستقبل أولى الترشيحات في اليوم نفسه.",
    "feat3_title": "سير ذاتية أقل بلا فائدة",
    "feat3_desc": "فلاتر دقيقة تستبعد الملفات غير المناسبة. ترى فقط الوكلاء المناسبين.",
    "feat4_title": "عمل جماعي",
    "feat4_desc": "ادعُ زملاءك، شارك الملاحظات وقرّروا معًا، دون واتساب.",
    "feat5_title": "أدوات بسيطة",
    "feat5_desc": "واجهة واضحة بالفرنسية والعربية. لا حاجة لأي تدريب.",
    "feat6_title": "جودة أفضل للمرشّحين",
    "feat6_desc": "استقطب وكلاء متحمّسين عبر صفحة إعلان احترافية بهويتك.",
    "adv_cta": "Découvrir l'espace recruteur",
    "vid_kicker": "شهادة",
    "vid_title": "يوظّفون وكلاءهم عبر كوان كارّيير",
    "vid_sub": "اكتشف كيف توقّفت وكالات عقارية مغربية عن المعاناة على فيسبوك.",
    "vid_media": "فيديو شهادة — مدير وكالة",
    "vid_cta": "انشر إعلاني",
    "stat1_num": "473+",
    "stats_kicker": "بالأرقام",
    "stats_title": "بعض الأرقام المفتاحية لكوان كارّيير",
    "stat1_label": "وكالة وشركة توظّف",
    "stat2_num": "+5 137",
    "stat2_label": "إعلان منشور",
    "stat3_num": "100%",
    "stat3_label": "مجاني للبدء",
    "final_kicker": "جاهز للتوظيف؟",
    "final_title": "توظيفك القادم يبدأ هنا",
    "final_sub": "أنشئ فضاء التوظيف الخاص بك وانشر أول إعلان في أقل من 5 دقائق.",
    "final_cta": "انشر إعلانك الآن",
    "final_note": "مجاني للبدء · دون بطاقة بنكية",
    "footer_tagline": "منصة التوظيف من الجيل الجديد.",
    "footer_privacy": "سياسة الخصوصية",
    "footer_copy": "© 2026 كوان كارّيير — جميع الحقوق محفوظة."
  }
}/*EDITMODE-END*/;

window.TWEAK_DEFAULTS = TWEAK_DEFAULTS;
